language: java

env:
  - CI=false

install:
  - mvn install -DskipTests=true -B -V

test:
  - mvn test -B

jdk:
- oraclejdk8

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)